[project]
name = "wgpu-mojo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Lukas Hermann", "Jehanlos <me@jehanlos.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
main = "mojo main.mojo"
clean = "magic clean"

[dependencies]
webgpu-headers = ">=0.0.0.2023.11.27.d2fec1,<0.0.0.2023.11.28"
glfw = ">=3.4,<4"
max = "~=nightly"
wgpu-native = "22.1.0.4.*"
