[project]
name = "wgpu-mojo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Lukas Hermann"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
platforms = ["osx-arm64"]

[tasks]
exec = "mojo main.mojo"
exec_c = "mojo main_cstyle.mojo"
clean = "magic clean"
# DO NOT RUN -- OUT OF DATE
# gen = "python gen_c.py webgpu.json && mojo format wgpu"

[dependencies]
webgpu-headers = ">=0.0.0.2023.11.27.d2fec1,<0.0.0.2023.11.28"
glfw = ">=3.4,<4"
python = ">=3.11.9,<3.12"
max = "~=nightly"
wgpu-native = "22.1.0.4.*"
